export const committeeToIssueMap: Record<string, string[]> = {
  "Energy and Natural Resources": ["Energy", "ENV", "Fuel", "Oil", "Gas", "Mining", "Nuclear", "Renewable"],
  "Finance": ["Tax", "Finance", "Banking", "Insurance", "Trade", "Tariff"],
  "Armed Services": ["Defense", "Military", "Veterans", "National Security", "Weapons"],
  "Commerce, Science, and Transportation": ["Telecom", "Technology", "Transportation", "Aviation", "Rail", "Shipping"],
  "Commerce": ["Telecom", "Technology", "Transportation", "Aviation"],
  "Judiciary": ["Justice", "Crime", "Immigration", "Antitrust", "Copyright", "Patent"],
  "Agriculture, Nutrition, and Forestry": ["Agriculture", "Food", "Farm", "Rural", "Nutrition"],
  "Agriculture": ["Agriculture", "Food", "Farm", "Rural"],
  "Health, Education, Labor, and Pensions": ["Health", "Pharma", "Medicare", "Medicaid", "Education", "Labor"],
  "Health": ["Health", "Pharma", "Medicare", "Medicaid"],
  "Appropriations": ["Budget", "Appropriations", "Spending", "Federal"],
  "Banking, Housing, and Urban Affairs": ["Banking", "Housing", "Real Estate", "Mortgage", "Financial"],
  "Banking": ["Banking", "Housing", "Financial"],
  "Budget": ["Budget", "Deficit", "Spending", "Fiscal"],
  "Environment and Public Works": ["Environment", "EPA", "Climate", "Infrastructure", "Highway"],
  "Foreign Relations": ["Foreign", "International", "Treaty", "Diplomacy", "Trade"],
  "Homeland Security and Governmental Affairs": ["Homeland", "Security", "FEMA", "Cybersecurity", "Government"],
  "Indian Affairs": ["Tribal", "Native", "Indian"],
  "Intelligence": ["Intelligence", "CIA", "NSA", "Surveillance"],
  "Rules and Administration": ["Election", "Voting", "Campaign"],
  "Small Business and Entrepreneurship": ["Small Business", "Entrepreneur", "SBA"],
  "Veterans' Affairs": ["Veterans", "VA", "Military"],
};
