import "dotenv/config";
import { config } from "dotenv";
config({ path: ".env.local" });
import { writeFileSync } from "fs";
import { join } from "path";
import {
  classifyFetchedSource,
  discoverPaCountyBoardSources,
  inventoryEntryForCountyWebsite,
} from "../src/lib/localElections/discover";
import { fetchOfficialText } from "../src/lib/localElections/fetchOfficial";
import { formatInventoryReport } from "../src/lib/localElections/inventory";
import { PA_DOS_COUNTY_CONTACTS_URL } from "../src/lib/localElections/inventory";
import { PRIORITY_STATE_ADMIN_NOTES } from "../src/lib/localElections/inventories/priorityStateNotes";
import type { LocalSourceInventoryEntry } from "../src/lib/localElections/inventory";

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

function electionLinks(html: string, baseUrl: string): string[] {
  const hrefs = [...html.matchAll(/href=["']([^"']+)["']/gi)].map((m) => m[1]);
  const out: string[] = [];
  for (const href of hrefs) {
    if (!/election|voter|vote|ballot/i.test(href)) continue;
    try {
      const url = new URL(href, baseUrl);
      if (url.origin !== new URL(baseUrl).origin) continue;
      if (out.includes(url.toString())) continue;
      out.push(url.toString());
    } catch {
      continue;
    }
    if (out.length >= 2) break;
  }
  return out;
}

async function probe(entry: LocalSourceInventoryEntry): Promise<LocalSourceInventoryEntry> {
  if (entry.sourceUrl === PA_DOS_COUNTY_CONTACTS_URL) return entry;
  const home = await fetchOfficialText(entry.sourceUrl, { timeoutMs: 12000 });
  if (home.ok === false) {
    const blocked = /HTTP 401|HTTP 403|HTTP 429/.test(home.error);
    return {
      ...entry,
      status: blocked ? "BLOCKED" : "UNAVAILABLE",
      accessMethod: "UNKNOWN",
      adapterRequired: false,
      notes: home.error,
      lastProbed: new Date().toISOString(),
    };
  }
  let classified = classifyFetchedSource({
    statusCode: home.status,
    url: entry.sourceUrl,
    body: home.text,
  });
  if (classified.status === "DISCOVERED") {
    for (const link of electionLinks(home.text, entry.sourceUrl)) {
      await sleep(250);
      const page = await fetchOfficialText(link, { timeoutMs: 12000 });
      if (page.ok === false) continue;
      const next = classifyFetchedSource({
        statusCode: page.status,
        url: link,
        body: page.text,
      });
      if (next.status === "VERIFIED") {
        return {
          ...inventoryEntryForCountyWebsite({
            countyName: entry.jurisdiction,
            sourceUrl: link,
            status: next.status,
            accessMethod: next.accessMethod,
            notes: next.notes,
          }),
          lastProbed: new Date().toISOString(),
        };
      }
      if (next.status === "PDF") classified = next;
    }
  }
  return {
    ...entry,
    status: classified.status,
    accessMethod: classified.accessMethod,
    adapterRequired: classified.status === "VERIFIED" || classified.status === "PDF",
    notes: classified.notes,
    lastProbed: new Date().toISOString(),
  };
}

function serializeTs(rows: LocalSourceInventoryEntry[]): string {
  return `import type { LocalSourceInventoryEntry } from "../inventory";

/** Generated by scripts/discover-local-sources.ts from official PA Department of State county links. */
export const PA_COUNTY_BOARD_SOURCES: LocalSourceInventoryEntry[] = ${JSON.stringify(rows, null, 2)};
`;
}

async function main() {
  const args = process.argv.slice(2);
  const probeEnabled = args.includes("--probe");
  const state = (
    args.find((a) => a.startsWith("--state="))?.slice("--state=".length) || "PA"
  ).toUpperCase();
  if (state !== "PA") {
    console.log(formatInventoryReport(`${state} local-source notes`, PRIORITY_STATE_ADMIN_NOTES.filter((r) => r.stateCode === state)));
    return;
  }
  console.log("Discovering PA county board websites from the Department of State directory...");
  let rows = await discoverPaCountyBoardSources();
  if (probeEnabled) {
    console.log(`Probing ${rows.length} official county URLs (no bot-protection bypass)...`);
    const probed: LocalSourceInventoryEntry[] = [];
    for (let i = 0; i < rows.length; i++) {
      if (i > 0) await sleep(300);
      const row = rows[i];
      process.stdout.write(`  ${row.jurisdiction}...\n`);
      probed.push(await probe(row));
    }
    rows = probed;
    const out = join(process.cwd(), "src/lib/localElections/inventories/paCountyBoards.ts");
    writeFileSync(out, serializeTs(rows), "utf8");
    console.log(`Wrote ${out}`);
  }
  console.log(
    formatInventoryReport("Pennsylvania", rows, {
      countyEquivalents: 67,
      countyElections: 0,
      municipalElections: 0,
      schoolElections: 0,
    })
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
